modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/rosevcook/windswepts_delights/issues"
license = "All Rights Reserved"

[[mods]]
    modId = "windswept_delights"
    version = "1.0.1"
    displayName = "Windswept Delights"
    logoFile = "logo.png"
    itemIcon = "windswept_delights:snow_cone"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/windsweptmod"
    authors = "Rose, Yape"
    description = '''Cross Content for Windswept and Farmers Delight'''

[[dependencies.windswept_delights]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.windswept_delights]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.windswept_delights]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.0,)"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.windswept_delights]]
    modId = "windswept"
    mandatory = true
    versionRange = "[3.0.0,)"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.windswept_delights]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.2.8,)"
    ordering = "BEFORE"
    side = "BOTH"
